### ISSUE TITLE
FEAT: Active position of draggable item

### ISSUE THREAD

**Issue by ZanaNabaz** [minhchienwikipedia/react-native-draggable-reanimated#2]
Could you add  "onActive" prop to this component?

and use:
runOnJS(onActive)({ x: ctx.endX, y: ctx.endY });

as you do to update on release?
I need this feature in my project.

**Comment by ZanaNabaz** [comment]
I created a PR please have a look #3

**Comment by minhchienwikipedia** [comment]
Thanks for your contribution, I have merged it
